### ISSUE TITLE
Compare Commons and OSM data

### ISSUE THREAD

**Issue by Discostu36** [Discostu36/OSM-Photos#27]
At a later point, a QA mode could be added. It could compare Commons categories with OSM data and ask the user about missing or inconsistent data. For example:

> The photo of this building is in the Wikimedia Commons category `Brick buildings in New York City`. Do you want to add `building:material=brick` to the OpenStreetMap object?

**Comment by matkoniecz** [comment]
I would double check is it OK from licensing side.

**Comment by Discostu36** [comment]
This is an important thing to keep in mind, thank you. The licences are actually really incompatible. So I have to make sure that this feature is only used for contributing user data, not misused as a migration tool. For example, the app could simply ask "Is this a brick building?". The idea of asking the question would still come from one of the two data sources, but the data itself would come from the user.

**Comment by matkoniecz** [comment]
I suspect that this phrasing is changing nothing from licensing point of view, as you still copy Commons data.

And anyway, app needs option also for other materials in case that Commons is wrong, so it ends with StreetComplete-like asking about `building:material` value.

**Comment by Discostu36** [comment]
I still believe that the data is not copied if a person does verify its correctness via survey. But maybe I'll just have to ask Wikimedia Foundation and OpenStreetMap Foundation to be sure.

You are right that asking about the correct material would be the next logical step. But I think it would already be enough, if the app added/removed the data depending on the answer.

I'll think about it in two years when the main functionality of the app is done 😄

**Comment by Discostu36** [comment]
Thanks again for the hint about license compatibility. I have created a separate issue for that: #30

**Comment by Discostu36** [comment]
Due to the negative answer by OSMF, plans to migrate any data from one project to the other are abandoned.
