### ISSUE TITLE
idea : automatic naming

### ISSUE THREAD

**Issue by JLZIMMERMANN** [Discostu36/OSM-Photos#32]
What needs time is to name each picture. In my idea we could gather the good informations for this :
Adress +number+city+country+ISO date

Here you have an example https://commons.wikimedia.org/wiki/Category:Shops_in_Orange_(Vaucluse)

**Comment by Discostu36** [comment]
Yes, that is part of the original idea, see Readme.

**Comment by JLZIMMERMANN** [comment]
"The app will automatically add fitting descriptions and categories to the Commons page of the file. It will then add the wikimedia_commons tag to the OSM object and upload that change to the OSM database." GOOD !
So in my post you have good one method ;-)

**Comment by Discostu36** [comment]
My initial idea is not possible due to legal reasons. See this issue for discussing how we can move on from here:

https://github.com/Discostu36/OSM-Photos/issues/33

**Comment by JLZIMMERMANN** [comment]
I have discussed with the former president of OpenStreetMap France that told me that adding a name to picture is not creating a database. You must just in the app tell that the information comes from OSM.
You can move forward ;-)
